# Generated by Django 6.0.3 on 2026-04-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
        ),
        migrations.AddField(
            model_name='feeitem',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feestructure'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='schoolpaymentmethod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school', 'student_class', 'term', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'fee_structure')},
        ),
    ]
