# Generated by Django 6.0 on 2026-01-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Invoice',
            new_name='invoice',
        ),
    ]
