# Generated by Django 6.0 on 2026-02-11 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_feestructure_is_active_feestructure_total_amount_and_more'),
        ('schools', '0003_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYBILL', 'Paybill'), ('BANK', 'Bank Transfer')], max_length=20)),
                ('details', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='schools.school')),
            ],
        ),
    ]
