# Generated by Django 6.0 on 2026-02-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_schoolpaymentmethod'),
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'fee_structure')},
        ),
    ]
