# Generated by Django 6.0 on 2026-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('chiefexercutiveofficer', 'C.E.O'), ('schooladmin', 'School Admin'), ('bursar', 'Bursar'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=100),
        ),
    ]
