# Generated by Django 6.0 on 2026-01-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='school',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='students',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
