# Generated by Django 6.0 on 2026-01-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teacherattendance_teacher_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubject',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsubject',
            name='subject',
        ),
        #migrations.RemoveField(
            #model_name='studentmark',
            #name='exam_subject',
        #),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assigned_teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='ExamSubject',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
