# Generated by Django 6.0 on 2026-01-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_examsubject_exam_remove_examsubject_subject_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
