# Generated by Django 6.0 on 2026-01-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_teacherattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='school',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='student',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='FeeItem',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
