# Generated by Django 6.0 on 2026-01-23 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicterm'),
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclass',
            unique_together={('teacher', 'school_class', 'subject')},
        ),
    ]
