# Generated by Django 6.0 on 2026-01-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_date_of_birth_teacher_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
