# Generated by Django 6.0 on 2026-01-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
