# Generated by Django 6.0 on 2026-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_studentmark_unique_together_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='academics.subject'),
        ),
    ]
