# Generated by Django 6.0 on 2026-01-07 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPLan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_students', models.PositiveIntegerField()),
                ('max_teachers', models.PositiveIntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.subscriptionplan'),
        ),
    ]
