# Generated by Django 6.0 on 2026-02-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schoolclass_subjects'),
        ('teachers', '0002_alter_teacherclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher_for', to='teachers.teacher'),
        ),
    ]
