# Generated by Django 6.0.3 on 2026-05-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subscription_active',
        ),
    ]
