# Generated by Django 6.0 on 2026-01-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0002_subscriptionplan_school_subscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject', 'school_class')},
        ),
    ]
