# Generated by Django 6.0 on 2026-01-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'school_class', 'term', 'year', 'name')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
    ]
