# Generated by Django 6.0 on 2026-01-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_examsubject_school_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='school_class',
        ),
    ]
