# Generated by Django 6.0.3 on 2026-04-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicterm_year'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicterm',
            old_name='name',
            new_name='term',
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('school', 'year', 'term')},
        ),
    ]
