# Generated by Django 6.0.3 on 2026-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rename_name_academicterm_term_and_more'),
        ('schools', '0004_remove_school_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='school_class',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='school_class',
            field=models.ManyToManyField(to='schools.schoolclass'),
        ),
    ]
