# Generated by Django 6.0 on 2026-01-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academicterm'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
