# Generated by Django 6.0.3 on 2026-05-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_studentmark_school_class_and_more'),
        ('schools', '0004_remove_school_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='school_class',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
        ),
    ]
