# Generated by Django 6.0.3 on 2026-06-24 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_studentmark_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
