# Generated by Django 6.0 on 2026-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_studentmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
