# Generated by Django 6.0 on 2026-01-29 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_exam_unique_together_alter_exam_school_class'),
        ('schools', '0002_schoolclass_subjects'),
        ('teachers', '0002_alter_teacherclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('Opener', 'Opener'), ('Mid-term', 'Mid-term'), ('End-term', 'End-term')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'school_class', 'term', 'year', 'name')},
        ),
    ]
