# Generated by Django 6.0 on 2026-01-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_exam_unique_together_studentmark_school_class_and_more'),
        ('schools', '0002_schoolclass_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'school_class', 'term', 'year')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
    ]
