# Generated by Django 6.0 on 2026-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_exam_unique_together_remove_exam_created_at_and_more'),
        ('schools', '0002_schoolclass_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'term', 'year')},
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='school_class',
        ),
    ]
