# Generated by Django 6.0 on 2026-01-29 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_exam_unique_together_exam_name_and_more'),
        ('schools', '0002_schoolclass_subjects'),
        ('students', '0002_alter_student_admission_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='studentmark',
            unique_together={('student', 'subject', 'exam')},
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmark',
            name='term',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_marks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'school_class', 'term', 'year', 'name')},
        ),
    ]
