# Generated by Django 6.0 on 2026-01-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_exam_unique_together_and_more'),
        ('schools', '0002_schoolclass_subjects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('school', 'term', 'year', 'name')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='school_class',
        ),
    ]
