# Generated by Django 6.0 on 2026-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('schools', '0002_schoolclass_subjects'),
        ('students', '0002_alter_student_admission_number'),
        ('teachers', '0002_alter_teacherclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day'),
        ),
    ]
